# --- INSTRUÇÕES PARA CRIAÇÃO DE SECRETS ---
# Os segredos reais NÃO devem ser versionados. Crie-os manualmente no cluster:
#
# kubectl create secret generic bff-secret -n academyio \
#   --from-literal=Jwt__Key='uma-chave-secreta-super-segura-para-producao'
# ------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-deployment
  namespace: academyio
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: luisfelipebcc/academyio-bff:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: bff-config
            - secretRef:
                name: bff-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: academyio
spec:
  selector:
    app: bff
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # Alterado para ClusterIP para uso com Ingress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-config
  namespace: academyio
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  DOTNET_RUNNING_IN_CONTAINER: "true"
  ASPNETCORE_URLS: "http://*:80"
  AppServicesSettings__AuthUrl: "http://auth-api-service"
  AppServicesSettings__CourseUrl: "http://courses-api-service"
  AppServicesSettings__StudentUrl: "http://students-api-service"
  AppServicesSettings__PaymentUrl: "http://payments-api-service"
