apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: {{DOCKERHUB_USERNAME}}/academyio-auth-api:latest # Substitua {{DOCKERHUB_USERNAME}} pelo seu usuário no Docker Hub
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: auth-api-config
            - secretRef:
                name: auth-api-secret
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api-service
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-api-config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  DOTNET_RUNNING_IN_CONTAINER: "true"
  ASPNETCORE_URLS: "http://*:8080"
  MessageBus__ConnectionString: "amqp://guest:guest@rabbitmq-service:5672/" # Aponta para o serviço do RabbitMQ no K8s
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-api-secret
type: Opaque
# --- ATENÇÃO ---
# Este arquivo é um template. Os segredos reais NÃO devem ser versionados.
# Crie o segredo no cluster Kubernetes antes de fazer o deploy.
#
# Exemplo de comando para criar o segredo:
# kubectl create secret generic auth-api-secret \
#   --from-literal=ConnectionStrings__DefaultConnection='Server=sqlserver-service;Database=AuthDb;User Id=sa;Password=<YourStrong!Passw0rd>;TrustServerCertificate=true' \
#   --from-literal=Jwt__Key='uma-chave-secreta-super-segura-para-producao'
#
# O campo 'stringData' foi omitido intencionalmente do controle de versão.
stringData: {}
