name: .NET CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Exemplo para a API de Pagamentos. Repita este bloco para cada serviço.
      - name: Build and push Payments API
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/services/AcademyIO.Payments.API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/academyio-payments-api:latest

    # Adicione aqui os steps para as outras APIs (Students, Auth, etc.)
    # - name: Build and push Students API
    #   uses: docker/build-push-action@v4
    #   with:
    #     ...
    #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/academyio-students-api:latest
