# --- INSTRUÇÕES PARA CRIAÇÃO DE SECRETS ---
# Os segredos reais NÃO devem ser versionados. Crie-os manualmente no cluster:
#
# kubectl create secret generic payments-api-secret -n academyio \
#   --from-literal=ConnectionStrings__DefaultConnection='Server=sqlserver-service;Database=PaymentsDb;User Id=sa;Password=<YourStrong!Passw0rd>;TrustServerCertificate=true' \
#   --from-literal=Payments__ProviderApiKey='sua-api-key-real-do-provedor'
# ------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api-deployment
  namespace: academyio
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
        - name: payments-api
          image: luisfelipebcc/academyio-payments-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: payments-api-config
            - secretRef:
                name: payments-api-secret
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-api-service
  namespace: academyio
spec:
  selector:
    app: payments-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-api-config
  namespace: academyio
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  DOTNET_RUNNING_IN_CONTAINER: "true"
  ASPNETCORE_URLS: "http://*:8080"
